server:
  port: 8888
  servlet:
    context-path: /springboot
spring:
  datasource:
    username: root
    password: 1173389434xy
    url: jdbc:mysql://localhost:3306/ssm_2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
